environment:
  matrix:
        - jdk: "C:\Program Files\Java\jdk1.8.0\bin:"
        WLP_VERSION: "17.0.0.2"

build_script:
  # Build the compiled extension
  - "gradlew.bat install check -Prunit=online -DwlpVersion=$WLP_VERSION --stacktrace --info"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
- path: build\*
